### ISSUE TITLE
Adding/Deleting columns is generating issues in case of custom column fields.

### ISSUE THREAD

**Issue by shivamsharma** [goibibo/SqlShift#27]
Error Stack :- 
```
java.sql.SQLException: [Amazon](500310) Invalid operation: cannot drop distkey column "columnName";
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(ErrorResponse.java:1830)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(PGMessagingContext.java:822)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(PGMessagingContext.java:647)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(InboundMessagesPipeline.java:312)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(PGMessagingContext.java:1080)
	at com.amazon.redshift.client.PGMessagingContext.getErrorResponse(PGMessagingContext.java:1048)
	at com.amazon.redshift.client.PGClient.handleErrorsScenario2ForPrepareExecution(PGClient.java:2446)
	at com.amazon.redshift.client.PGClient.handleErrorsPrepareExecute(PGClient.java:2387)
	at com.amazon.redshift.client.PGClient.executePreparedStatement(PGClient.java:1373)
	at com.amazon.redshift.dataengine.PGQueryExecutor.executePreparedStatement(PGQueryExecutor.java:370)
	at com.amazon.redshift.dataengine.PGQueryExecutor.execute(PGQueryExecutor.java:245)
	at com.amazon.jdbc.common.SPreparedStatement.executeWithParams(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.execute(Unknown Source)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(RedshiftJDBCWrapper.scala:129)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(RedshiftJDBCWrapper.scala:129)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$2.apply(RedshiftJDBCWrapper.scala:147)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
```

**Comment by ShahSunny** [comment]
Ideally This looks like a case which can't be automated.
